### ISSUE TITLE
Currencies are overwritten after a new compute cycle

### ISSUE THREAD

**Issue by worldworm** [Lissy93/all-the-countries#1]
Hello there!
first of all: what a nice little project! 💎 

I noticed that when you first load the page, the currency for each country is filled correctly. However, as soon as you search for a country, the currency is directly replaced by "undefined (undefined)".
![grafik](https://user-images.githubusercontent.com/13227454/181365281-1f95845a-008e-4db4-a001-599e810757aa.png)

After a bit of fiddling around, it seems to me that it's because the data is created in a [computed properties](https://github.com/Lissy93/all-the-countries/blob/409cfed55e14d1bd30f7ef2b059c0ab34cf1a20a/src/pages/Index.vue#L41), which [overwrites the object country itself](https://github.com/Lissy93/all-the-countries/blob/409cfed55e14d1bd30f7ef2b059c0ab34cf1a20a/src/utils/formatRawData.js#L46) in the [formatRawData](https://github.com/Lissy93/all-the-countries/blob/409cfed55e14d1bd30f7ef2b059c0ab34cf1a20a/src/utils/formatRawData.js#L29)
And if I understand [stackoverflow ](https://stackoverflow.com/questions/53925103/why-does-computed-change-data-when-assigning-data-to-a-variable) correctly, computed properties seem to be "call by reference" and thus modify the [RawCountriesData ](https://github.com/Lissy93/all-the-countries/blob/409cfed55e14d1bd30f7ef2b059c0ab34cf1a20a/src/pages/Index.vue#L32) object. (but I can be completely wrong)

I would love to help and try to fix it. I'm not sure what the right approach is here though.

- I could move the whole thing from computed to a method. However, I would have said it is correct in a computed.
- I could map the whole object in the [formatRawData](https://github.com/Lissy93/all-the-countries/blob/409cfed55e14d1bd30f7ef2b059c0ab34cf1a20a/src/utils/formatRawData.js#L29) into a completely new object so as not to touch the original object. But that's not nice either somehow.
- A small if statement [here ](https://github.com/Lissy93/all-the-countries/blob/409cfed55e14d1bd30f7ef2b059c0ab34cf1a20a/src/utils/formatRawData.js#L43) to check if it has already been converted

Do you have a suggestion or a better idea? 😅 
Please let me know and I would be happy to create a pull request.

**Comment by lissy93** [comment]
Heya @worldworm
Yay someone's actually using my project 🤗

Thank you for the very detailed bug report, your diagnosis is absolutely correct.

I think the easiest fix, is like you suggested, to just check if currencies is already an array, [here](https://github.com/Lissy93/all-the-countries/blob/master/src/utils/formatRawData.js#L43-L46). This should fix it:

```diff
+ if (!Array.isArray(country.currencies)) {
   Object.values(country.currencies).forEach((currencyObj) => {
     currencies.push(`${currencyObj.name} (${currencyObj.symbol})`);
   });
   country.currencies = currencies;
+ }
```    

If you'd be up for submitting a PR, that'd be awesome. But otherwise I can implement this myself tomorrow morning :)
